# Generated by Django 5.1.4 on 2024-12-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('department', models.CharField(max_length=122)),
                ('email', models.CharField(max_length=40)),
                ('password', models.CharField(max_length=15)),
                ('date', models.DateField()),
            ],
        ),
    ]
