# Generated by Django 5.1.4 on 2025-01-02 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='department',
            field=models.CharField(blank=True, max_length=122),
        ),
    ]
